name: iOS Build & Export IPA

on:
  push:
    branches:
      - main  # Chạy khi có push vào nhánh main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: 🔍 Show available Xcode versions
        run: ls /Applications | grep Xcode

      - name: 📌 Install dependencies (nếu có SPM)
        run: xcodebuild -resolvePackageDependencies

      - name: 🏗️ Build & Archive app
        run: |
          xcodebuild -project SwipeIt.xcodeproj \
                     -scheme SwipeIt \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/SwipeIt.xcarchive archive

      # 5. Xuất file IPA
      - name: Export IPA
        run: |
          cd swipe-it-swift
          xcodebuild -exportArchive \
            -archivePath output/SwipeIt.xcarchive \
            -exportPath output/ \
            -exportOptionsPlist ExportOptions.plist

      # 6. Upload file IPA vào Artifact (Tải xuống từ GitHub Action)
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwipeIt.ipa
          path: swipe-it-swift/output/*.ipa
