name: SwiftFormat Check

on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  swift-format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftFormat
        run: |
          brew install swift-format

      - name: Run SwiftFormat and fix
        run: |
          swift-format format --in-place --recursive .

      - name: Commit changes
        run: |
		  git config --global user.name "Anh Huân Lê"
		  git config --global user.email "your_email@example.com"
		  git add .
		  git commit -m "Apply swift linting + formatting"
		  git push

